apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.config }}
  config.yml: {{ .Values.config | b64enc | quote }}
  {{- else }}
  config.yml: {{ "channels: []\n" | b64enc | quote }}
  {{- end }}
