apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  config.yml: {{ .Values.config | default "channels: []\n" | b64enc | quote }}
{{- with .Values.secrets.envs }}
stringData:
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
